soketi/soketi

.github/workflows/docker-commit.yml
.github/workflows/docker-latest-tag.yml
Dockerfile

[fix] Docker compatibility

---

jest.config.js
src/app.ts
src/http-handler.ts
tests/public.test.ts

[fix] Fix wrong token caused by forward slashes

---

src/ws-handler.ts

Sometimes channels show more subscribers than real subscribed to the channel.
This PR force close websocket if it is inactive over 120 seconds(4x ping time).

[0.x] Check for Socket timeout via pusher:pong

---

.github/workflows/ci.yml
.github/workflows/docker-commit.yml
.github/workflows/docker-latest-tag.yml
.github/workflows/docker-release-tag.yml
package.json
src/adapters/adapter-interface.ts
src/adapters/adapter.ts
src/adapters/local-adapter.ts
src/adapters/redis-adapter.ts

[fix] Node.js v16

---

src/adapters/local-adapter.ts
src/adapters/redis-adapter.ts
src/app-managers/dynamodb-app-manager.ts
src/app.ts
src/channels/presence-channel-manager.ts
src/channels/private-channel-manager.ts
src/http-handler.ts
src/metrics/metrics.ts
src/namespace.ts
src/queues/redis-queue-driver.ts
src/queues/sync-queue-driver.ts
src/server.ts
src/ws-handler.ts
tests/http-api.test.ts

[0.x] Send HTTP headers when needed 

---

src/cli/cli.ts
src/metrics/prometheus-metrics-driver.ts
src/options.ts
src/server.ts

[0.x] Drop hard-coded labels for Prometheus metrics

---

src/app.ts

Closes #133 
Possibly related: #66

[fix] Fixed JSON array parsing for the `webhooks` field

---

.gitignore
Dockerfile
benchmark/composer.json
benchmark/k6-big.js
benchmark/k6-medium.js
benchmark/k6-small.js
benchmark/send
benchmark/send.php

https://pws.soketi.app/benchmarks

[feature] K6 Benchmarking

---

src/http-handler.ts
src/log.ts
src/server.ts
src/webhook-sender.ts
src/ws-handler.ts

[feature] Added logs to debug webhooks

---

package.json
src/app-managers/mysql-app-manager.ts
src/cli/cli.ts
src/options.ts
src/server.ts
tests/utils.ts

[fix] Added optional `mysql2` client to fix MySQL8 authentication

---

package.json

[fix] Forcing bullmq to `1.57.3`

---

.gitignore
src/cli/cli.ts
src/cli/index.ts

[feature] Configuration file support

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/docker-latest-distroless-tag.yml
.github/workflows/docker-latest-tag.yml
.github/workflows/docker-release-distroless-tag.yml
.github/workflows/docker-release-tag.yml
.github/workflows/release-npm.yml

I've restricted the GHA versions (where possible) since that is best practice.
Next to that I have also worked on trying to speedup the GHA workflows by adding more `if`'s.

Bump and restrict GHA versions

---

package.json

Combining multiple dependencies PRs into one.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* Update @typescript-eslint/parser requirement from ^5.8.1 to ^5.9.0 (#264) @dependabot
* Update @typescript-eslint/eslint-plugin requirement from ^5.8.1 to ^5.9.0 (#260) @dependabot
* Update @types/node requirement from ^16.11.12 to ^16.11.19 (#259) @dependabot

Combined dependencies PR

---

src/webhook-sender.ts

Ref: https://github.com/soketi/soketi/pull/249

[fix] Webhooks send wrong signature when applied filtering

---

src/app-managers/dynamodb-app-manager.ts
src/channels/public-channel-manager.ts

[fix] Reject connections if `pusher:connection_established` is not received

---

src/cli/cli.ts

[fix] PM2 throws error because of config read from yargs

---

src/log.ts
src/server.ts

This PR improves the Log output, with some more margins and paddings.
PS: There is a need to have a [Termwind](https://github.com/nunomaduro/termwind) version on JS. 😎

feat: Improve logging styling.

---

src/webhook-sender.ts
tests/webhooks.test.ts

[fix] Use a fresh set of `payload.events` after each webhook check

---

src/ws-handler.ts
tests/ws.test.ts

[feature] Metadata

---

package.json
src/adapters/adapter-interface.ts
src/adapters/adapter.ts
src/adapters/horizontal-adapter.ts
src/adapters/local-adapter.ts
src/app.ts
src/channels/private-channel-manager.ts
src/channels/public-channel-manager.ts
src/cli/cli.ts
src/http-handler.ts
src/message.ts
src/namespace.ts
src/options.ts
src/server.ts
src/utils.ts
src/ws-handler.ts
tests/fixtures/dynamodb_schema.js
tests/http-api.cluster-adapter.test.ts
tests/http-api.nats-adapter.test.ts
tests/http-api.redis-adapter.test.ts
tests/http-api.test.ts
tests/presence.test.ts
tests/private.test.ts
tests/utils.ts
tests/ws.test.ts

[feature] Authenticated users

---

src/http-handler.ts

[feature] Added failsafes for responses

---

Dockerfile
Dockerfile.debian
Dockerfile.distroless

this would fix https://github.com/soketi/soketi/issues/832 to allow builds on different platforms than the target platform
further it would fix the alpine image to work again https://github.com/soketi/soketi/issues/747

[fix] Docker Alpine Linux startup and build target

---

.gitignore
src/cli/cli.ts

I suggest adding an uncaughtException handler to gracefully terminate the application when unhandled errors occur. The application will be able to properly close all connections and unsubscribe from the Redis when scaling horizontally

handle uncaughtException
