docs/ENV.md, src/cli/cli.ts, src/options.ts, src/server.ts
This PR adds support for the [`ioredis` options `username` and `db`](https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options), which are quite common ones to be used in production. There isn't really much to it, the new environment variables are passed down to the adapter similar to `DB_REDIS_PORT` for example.
=> [0.x] Support username and database index options for the Redis adapter

src/namespace.ts, tests/http-api.redis-adapter.test.ts, tests/presence.test.ts, tests/private.test.ts
Sometimes sockets still present in channels sets after disconnecting. 
I still could not find out why this happens.
=> [0.x] Cleanup channels on removeSocket()

src/ws-handler.ts
Was setting this up and accidentally sent invalid JSON to the server when I was testing with websocat.  It appears the JSON.parse had no error handling so it crashed the process.  This try / catch seems to tidy things up!
Great work on this package by the way!
=> Handle invalid json in messages

src/cli/cli.ts, src/options.ts, src/server.ts
This PR adds the capability to add a `pathPrefix` to all the urls.
The main usage will be to people that use proxies like `traefik` or `k8s ingress controller`, this way on a domain `https://example.com` can the be web server and `https://example.com/ws` will be the pWS server both working on the same port.
Hope this is helpful.
Thanks,
Francisco
=> [0.x] Add parameter to prefix the route URLs

.github/workflows/docker-commit.yml, src/app.ts, src/webhook-sender.ts, tests/webhooks.test.ts
Fixes #137.
---
I've also added a little refactor to defer doing any real work for the webhook sending to the queue handler which is probably better for the socket server because a webhook is now a simple queue action instead of doing hmac calculation even when no webhooks are even defined. But feel free to revert / remove that commit if that is incorrect or unwanted.
=> Fix webhook payload format

src/http-handler.ts, src/server.ts, src/ws-handler.ts
Closes #169 
This might break your app if you are seeking WebSocket statuses.
- Added a `/ready` endpoint to check if the server is pending closing (in Kubernetes you don't need that; use [Network Watcher](https://github.com/soketi/network-watcher) instead)
- When closing sockets, the command will send a [WebSocket Code](https://www.iana.org/assignments/websocket/websocket.xhtml) to mark the reason. In pusher this is irrelevant, but most are related to pending closing instances
- If the server is pending closing, the server will not allow existing sockets to subscribe to new channels, and will instead throw the `4200` code in Pusher (meaning reconnect immediately after) and close the socket
=> [fix] Closing safety checks

.github/workflows/docker-latest-distroless-tag.yml, .github/workflows/docker-latest-tag.yml, .github/workflows/docker-release-distroless-tag.yml, .github/workflows/docker-release-tag.yml, Dockerfile, Dockerfile.distroless
This work hardens the existing dockerfile in two ways:
- by using a [distroless](https://github.com/GoogleContainerTools/distroless) image and,
- by running as a nonroot user. 
The advantage of using a distroless container is that, in the case of a remote code execution vulnerability the attacker cannot open a shell because there are not shells installed in the container. This makes an attack quite a bit harder to pull off, but can also make running something like `kubectl exec <your soketi pod> -- /bin/bash` to debug harder as, again, there is no shell in the container. I understand if that isn't a trade off the maintainers want to make, but I thought I'd show that its possible 😄
The advantage of a nonroot user is that in many container runtime environments the root user in a container …
=> Switch to distroless container image and nonroot user

.dockerignore
**This issue is not a security concern.**
For DynamoDB testing, soketi uses [DynamoDbLocal](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html). This server comes with additional files for it, like the recent [Log4j RCE vulnerability](https://www.whitesourcesoftware.com/resources/blog/log4j-vulnerability-cve-2021-45105/) which [are committed to the repo](https://github.com/soketi/soketi/tree/d1171f2400be3b764c2f376fdec0b9a409be72da/tests/fixtures/dynamodb/DynamoDBLocal_lib).
Docker seems to be adding them, but later on, it removes them in the process of building the Docker image. However, they still can be tracked in the Docker image layers' trace. To avoid false positives from automatic RCE checkers, they are removed from being added in the context …
=> [fix] Remove obsolete files (including Log4j) from context

src/app.ts, src/webhook-sender.ts, tests/webhooks.test.ts
In our app we have a lot of traffic on channels. For our purposes only a few channels need to actually fire a webhook so our app can track it's state. Adding a filter on the channel name for the webhook allow us to cut down on the amount of "useless" webhook traffic.
I propose we add a `channel_starts_with` and `channel_ends_with` option to a webhook that has to match before a webhook is fired (if both are defined both need to match). I opted to keep this as simple as possible and not try to deal with regex or multiple matchers per webhook but if wanted we can always discuss on how to do that the best.
Let me know what you think!
=> [feature] Allow webhooks to define filters on the start and/or end of the channel name

src/app.ts, src/webhook-sender.ts, tests/webhooks.test.ts
Title is pretty descriptive here I think :)
Also removed the `enableClientMessages` in the webhook tests where client events are not used to prevent confusion.
=> Ability to configure custom headers for webhooks

src/queues/queue.ts, src/queues/redis-queue-driver.ts, src/queues/sync-queue-driver.ts
So as it turns out the default job options for the Redis queue were causing jobs to never be processed.
> Delayed jobs will only be processed if there is at least one QueueScheduler instance configured in the Queue.
> https://docs.bullmq.io/guide/jobs/delayed
These are our default job options `defaultJobOptions: { attempts: 6, delay: 1000 },`.
So because of the delay and not having a `QueueScheduler` they are never ever processed :)
I've set some options to have an exponential backoff for failed job which I think was the original idea behind the `delay` option in being here in the first place and also added the needed `QueueScheduler` so jobs are properly scheduled once delayed.
The `removeOnComplete` and `removeOnFail` options remove the job information from Redis once they are completed …
=> Fix default Redis queue job options

src/http-handler.ts
Sending empty POST requests would crash the server:
```
C:\Users\renno\Desktop\package-tester\packages\uws\dist\http-handler.js:365    
return res.writeStatus(status)
^
Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
at HttpHandler.sendJson (C:\Users\renno\Desktop\package-tester\packages\uws\dist\http-handler.js:365:20)
at HttpHandler.badResponse (C:\Users\renno\Desktop\package-tester\packages\uws\dist\http-handler.js:210:21)
at C:\Users\renno\Desktop\package-tester\packages\uws\dist\http-handler.js:237:25
at C:\Users\renno\Desktop\package-tester\packages\uws\dist\http-handler.js:341:29
```
=> [fix] Do not close the connection on empty POST payload

package.json, src/adapters/adapter-interface.ts, src/adapters/adapter.ts, src/adapters/horizontal-adapter.ts, src/adapters/local-adapter.ts, src/channels/presence-channel-manager.ts, src/channels/private-channel-manager.ts, src/channels/public-channel-manager.ts, src/cli/cli.ts, src/http-handler.ts, src/index.ts, src/job.ts, src/message.ts, src/namespace.ts, src/options.ts, src/presence-member.ts, src/server.ts, src/ws-handler.ts, tests/http-api.test.ts, tests/utils.ts
Closes #238
As explained here: https://pusher.com/docs/channels/library_auth_reference/rest-api/#post-batch-events-trigger-multiple-events
- Moved PresenceMember class to the presence channel manager
- Added type hints for messages
- On `/events` and `/batch_events`, when the message payload is too big, it throws 413 instead of `400`
- Added `/batch_events` call and a variable `EVENT_MAX_BATCH_SIZE=10` to define the maximum amount of messages per batch
Caveats:
- `?info=` is not supported (yet). Filtering options will be added in a later version (alongside with [`/channels`'s filtering](https://pusher.com/docs/channels/library_auth_reference/rest-api/#get-channels-fetch-info-for-multiple-channels))
=> [feature] `/batch_events` call

src/adapters/adapter-interface.ts, src/adapters/adapter.ts, src/adapters/horizontal-adapter.ts, src/adapters/local-adapter.ts, src/channels/presence-channel-manager.ts, src/http-handler.ts, src/namespace.ts, src/ws-handler.ts
There was a missing type on the `PresenceMember`'s `user_info` that @stayallive pointed out.
Given this `PresenceMember`:
```typescript
export interface PresenceMemberInfo {
[key: string]: any;
}
export interface PresenceMember {
user_id: number|string;
user_info: PresenceMemberInfo;
socket_id?: string;
}
```
It seems like the entire time, adapters would return maps with `user_id` as key and `user_info` as value as opposed to their "Promise" to return `PresenceMember`. After this fix, the hints would look ok as described below.
To clear out, when retrieving presence members with adapters there is one return type and the `ws.presence` within the WebSocket connection is another type.
- `ws.presence` stores channel names as keys and `{ user_info, user_id }` objects as values
- Adapters …
=> [fix] Presence members' types

src/app-managers/dynamodb-app-manager.ts, src/options.ts, src/server.ts
Fixes #224 
Basically, the default config option is an empty string, which the AWS client tries to connect to and fails. Errors are ignored, so after a load of debugging I realised this was the case - setting the default to null fixes the issue.
I also added logging to failed dynamodb load requests, eg if someone configured the table wrong or w/e. Seems strange this is not enabled with `debug=1` previously.
=> [fix] DynamoDB invalid default endpoint

src/cli/cli.ts, src/options.ts, src/server.ts
It seems like the CA file path [is not documented](https://unetworking.github.io/uWebSockets.js/generated/interfaces/AppOptions.html) but [it exists](https://github.com/uNetworking/uWebSockets.js/blob/a13b497b31/src/AppWrapper.h#L437)
=> [feature] Add CA certificate option

.github/workflows/benchmark.yml, .github/workflows/ci.yml, src/adapters/cluster-adapter.ts, src/adapters/horizontal-adapter.ts, src/adapters/nats-adapter.ts, src/adapters/redis-adapter.ts, src/cli/cli.ts, src/options.ts, src/server.ts
Lowered timeout to 2s
Made resolvers better
Now in case timeout is reached, the promise gets resolved instantly.
=> [feature/fix] Resolve promises in case timeout is reached looking for another nodes' responses in horizontal scaling

README.md
Looks like the documentation moved out to another repository?
=> Update links to the documentation that 404.

src/cli/cli.ts
Was setting up Soketi earlier, spent about 15 minutes trying to figure out why my config wasn't loading before I realised I'd missed a comma
Thought this would be helpful. Let me know what you think.
=> Inform the user that their JSON config is invalid

src/http-handler.ts
Despite not being part of the Pushers API, this addition does not impact any implementation that makes use of this endpoint. 
It will add the user_info attribute to the object that already exists, opening up new possibilities for use.
=> [feature] Return `user_info` on the `/users` HTTP endpoint 

src/cli/cli.ts, src/webhook-sender.ts
Runs a filter on the events array, then makes sure the events array isn't empty before generating the signature and sending the webhook
=> [Fix] Webhook filtering when batching is enabled

src/log.ts
This PR fixes #451, by detecting if the message is not a string, and output just a `console.log`.
=> fix: Not logging non string output.

src/cache-managers/memory-cache-manager.ts
Makes sure we only delete cache items when they're past their TTL, rather than before
=> [fix/0.x] Make sure current time is after the cache expiry before removing, on the memory cache driver

src/metrics/prometheus-metrics-driver.ts
For some reason, the Prometheus metrics required getting the total sockets count globally. Local ones are alright, and they don't even require something else than `.inc()` and `.dec()` on the gauges.
This will ease the traffic more in case you have metrics enabled on horizontal scaling infra.
=> [1.x] Get rid of gathering the total sockets count in Prometheus
